name: lcs-aws-kubectl
description: "Action to provide kubectl on Github Actions."
author: 'LocalCoinSwap'
branding:
    color: 'white'
    icon: 'command'
runs:
  using: 'docker'
  image: 'Dockerfile'
